<?php
/**
 * Created V/12/04/2019
 * Updated M/31/08/2021
 *
 * Copyright 2019-2021 | Fabrice Creuzot <fabrice~cellublue~com>
 * Copyright 2019-2021 | Jérôme Siau <jerome~cellublue~com>
 * https://github.com/kyrena/openmage-shippingmax
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$help   = $this->helper('shippingmax');
$groups = $this->getShippingRates();
$shippingCodePrices = [];
?>

<?php if (empty($groups)): ?>
	<p><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></p>
<?php else: ?>
	<dl class="sp-methods">
	<?php $sole = count($groups) == 1; foreach ($groups as $code => $rates): ?>
		<dt class="<?php echo $code ?>">
			<?php echo $help->escapeEntities($this->getCarrierName($code)) ?>
			<?php if (!empty($desc = Mage::getStoreConfig('carriers/'.$code.'/description'))): ?>
				<div class="desc"><?php echo $desc ?></div>
			<?php endif ?>
		</dt>
		<dd class="<?php echo $code ?>">
			<?php if ($help->isSpecial($code)): ?>
				<?php $rate = reset($rates) ?>
				<?php if ($rate->getErrorMessage()): ?>
					<ul class="messages">
						<li class="error-msg"><?php echo $help->escapeEntities($rate->getErrorMessage()) ?></li>
					</ul>
				<?php else: ?>
					<?php echo $this->getChild('shippingmax_selected')->setData('code', $code)->toHtml() ?>
				<?php endif ?>
			<?php else: ?>
				<ul>
					<?php $sole = $sole && count($rates) == 1; foreach ($rates as $rate): ?>
						<?php $shippingCodePrices[] = "'".$rate->getCode()."':".(float)$rate->getPrice() ?>
						<li>
							<?php if ($rate->getErrorMessage()): ?>
								<ul class="messages">
									<li class="error-msg"><?php echo $help->escapeEntities($rate->getErrorMessage()) ?></li>
								</ul>
							<?php else: ?>
								<?php if ($sole): ?>
									<input name="shipping_method" type="radio" value="<?php echo $rate->getCode() ?>" id="s_method_<?php echo $rate->getCode() ?>" checked="checked" class="no-display" />
								<?php else: ?>
									<?php if ($rate->getCode() == $this->getAddressShippingMethod()): ?>
										<input type="radio" name="shipping_method" value="<?php echo $rate->getCode() ?>" checked="checked" class="radio" id="s_method_<?php echo $rate->getCode() ?>" />
										<script type="text/javascript">lastPrice = <?php echo (float) $rate->getPrice() ?>;</script>
									<?php else: ?>
										<input type="radio" name="shipping_method" value="<?php echo $rate->getCode() ?>" class="radio" id="s_method_<?php echo $rate->getCode() ?>" />
									<?php endif ?>
								<?php endif ?>

								<label for="s_method_<?php echo $rate->getCode() ?>">
									<?php echo $help->escapeEntities($rate->getMethodTitle()) ?>
									<?php $excl = $this->getShippingPrice($rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()) ?>
									<?php $incl = $this->getShippingPrice($rate->getPrice(), true) ?>
									<?php echo $excl ?>
									<?php if (($incl != $excl) && $this->helper('tax')->displayShippingBothPrices()): ?>
										(<?php echo $this->__('Incl. Tax') ?> <?php echo $incl ?>)
									<?php endif ?>
								</label>
						   <?php endif ?>
						</li>
					<?php endforeach ?>
				</ul>
			<?php endif ?>
		</dd>
	<?php endforeach ?>
	</dl>

	<?php if (!empty($shippingCodePrices)): ?>
		<script type="text/javascript">//<![CDATA[
		var shippingCodePrice = {<?php echo implode(',', $shippingCodePrices) ?>};
		//]]></script>
	<?php endif ?>
<?php endif ?>