<?php
/**
 * Created V/12/04/2019
 * Updated J/25/11/2021
 *
 * Copyright 2019-2022 | Fabrice Creuzot <fabrice~cellublue~com>
 * Copyright 2019-2022 | Jérôme Siau <jerome~cellublue~com>
 * https://github.com/kyrena/openmage-shippingmax
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$help    = $this->helper('shippingmax');
$code    = $this->getData('code');    // code du mode de livraison ou id de la commande
$items   = $this->getData('items');   // liste des points de livraison
$address = $this->getData('address'); // adresse de livraison
$active  = $this->getData('selected');
$isGeo   = $this->getData('geoloc');

$useStreet = ($address->getData('country_id') == 'RU') && Mage::getStoreConfigFlag('carriers/shippingmax/search_by_street');
?>

<?php if (!empty($items)): ?>
	<?php echo $this->getChildHtml('messages') ?>
	<ul class="results-list">
		<?php $idx = 1; foreach ($items as $id => $item):
			$item = new Varien_Object($item);
		?>
			<li class="<?php echo ($id == $active) ? 'item i'.$idx.' active' : 'item i'.$idx ?>" id="pt<?php echo $id ?>" onclick="shippingmax.goToMarkerFromDetail(this);">
				<div class="item-container">
					<div class="item-card_details">
						<h2 class="name" title="<?php echo $help->escapeEntities($item->getData('name')) ?> (<?php echo $item->getId() ?>)">
							<?php if (!empty($item->getData('carrier'))): ?>
								<span class="icn ic-<?php echo str_replace(['shippingmax_', 'cash'], '', $item->getData('carrier')) ?>" title="<?php echo $help->escapeEntities(Mage::getStoreConfig('carriers/shippingmax_'.str_replace('shippingmax_', '', $item->getData('carrier')).'/img_title')) ?>"></span>
							<?php else: ?>
								<span class="icn ic-<?php echo str_replace(['shippingmax_', 'cash'], '', $code) ?>" title="<?php echo $help->escapeEntities(Mage::getStoreConfig('carriers/'.$code.'/img_title')) ?>"></span>
							<?php endif ?>
							<span class="pname"><?php echo $item->getData('name') ?></span> <small class="pid">(<?php echo $item->getId() ?>)</small>
						</h2>
						<address class="addr">
							<?php echo preg_replace('#^\s+<br ?/?>#', '', Mage::getModel('customer/address')->addData($item->getData())->format('html')) ?>
						</address>
						<?php if (!empty($desc = $item->getData('description'))): ?>
							<p class="desc"><?php echo $help->formatDesc($desc) ?></p>
						<?php endif ?>
					</div>
					<?php if (!is_numeric($code)): ?>
						<?php if (!empty($item->getData('dst'))): ?>
							<div class="dist-store"><em><?php echo ($item->getData('dst') > 1) ? round($item->getData('dst')) : '&lt;1' ?> km</em></div>
						<?php endif ?>
						<?php if ($code != 'shippingmax_storelocator'): ?>
							<input type="radio" name="id" value="<?php echo $id ?>" <?php echo ($id == $active) ? 'checked="checked"' : '' ?> />
							<button type="submit" onclick="this.parentNode.querySelector('input').checked = true;">
								<?php echo $this->__('Choose this location') ?>
							</button>
						<?php endif ?>
					<?php endif ?>
					<?php if (($code == 'shippingmax_storelocator') && is_file(Mage::getBaseDir('media').'/wysiwyg/storelocator/'.$id.'.jpg')): ?>
						<img src="<?php echo Mage::getBaseUrl('media'),'wysiwyg/storelocator/',$id,'.jpg' ?>" alt="" class="screen" />
					<?php endif ?>
				</div>
			</li>
		<?php $idx++; endforeach ?>
	</ul>
<?php elseif (empty($address->getData('postcode')) && empty($address->getData('city'))): ?>
	<?php //echo $this->getChildHtml('messages') ?>
	<p><?php echo $useStreet ? $this->__('Please enter your street (or your postal code) and city.') : $this->__('Please enter your postal code and city.') ?></p>
<?php elseif (empty($address->getData('postcode'))): ?>
	<?php //echo $this->getChildHtml('messages') ?>
	<p><?php echo $useStreet ? $this->__('Please enter your street (or your postal code).') : $this->__('Please enter your postal code.') ?></p>
<?php elseif (empty($address->getData('city'))): ?>
	<?php //echo $this->getChildHtml('messages') ?>
	<p><?php echo $this->__('Please enter your city.') ?></p>
<?php elseif (!empty($isGeo)): ?>
	<?php echo $this->getChildHtml('messages') ?>
	<div class="box">
		<?php $country = $address->getData('geo_country_id') ?>
		<p><?php echo $this->__('There are no results.') ?></p>
		<p><?php echo $this->__('Please check:') ?>
		<br />- <?php echo ($useStreet && ($country == 'RU')) ? $this->__('your street (or postal code):') : $this->__('your postal code:') ?> <strong><?php echo $address->getData('geo_postcode') ?></strong>
		<br />- <?php echo $this->__('your city:') ?> <strong><?php echo $address->getData('geo_city') ?></strong>
		<?php if (!empty($country)): ?>
			<br />- <?php echo $this->__('your country:') ?> <strong><?php echo Mage::getModel('directory/country')->loadByCode($country)->getName() ?></strong>
		<?php endif ?></p>
	</div>
<?php else: ?>
	<?php echo $this->getChildHtml('messages') ?>
	<div class="box">
		<p><?php echo $this->__('There are no results.') ?></p>
		<p><?php echo $this->__('Please check:') ?>
		<br />- <?php echo $useStreet ? $this->__('your street (or postal code):') : $this->__('your postal code:') ?> <strong><?php echo $address->getData('postcode') ?></strong>
		<br />- <?php echo $this->__('your city:') ?> <strong><?php echo $address->getData('city') ?></strong>
		<br />- <?php echo $this->__('your country:') ?> <strong><?php echo Mage::getModel('directory/country')->loadByCode($address->getData('country_id'))->getName() ?></strong></p>
	</div>
<?php endif ?>