<?php
/**
 * Created V/12/04/2019
 * Updated M/24/01/2023
 *
 * Copyright 2019-2023 | Fabrice Creuzot <fabrice~cellublue~com>
 * Copyright 2019-2022 | Jérôme Siau <jerome~cellublue~com>
 * https://github.com/kyrena/openmage-shippingmax
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

// root (root.phtml)
//  maphead
//  mapbody (map.phtml)
//   maplist (list.phtml) <= here
//    messages

$help      = $this->helper('shippingmax');       // (object) Kyrena_Shippingmax_Helper_Data
$model     = Mage::getModel('customer/address'); // (object) Mage_Customer_Model_Address
$address   = $this->getData('address');          // (object) adresse de livraison
$code      = $this->getData('code');             // (string) code du mode de livraison ou id de la commande
$items     = $this->getData('items');            // (array) liste des points de livraison
$selected  = $this->getData('selected');         // (string)
$isGeoloc  = $this->getData('geoloc');           // (bool)
$isShowAll = $this->getData('showAll');          // (bool)

$title     = Mage::getStoreConfig('carriers/'.$code.'/img_title'); // titre de l'icône
$title     = empty($title) ? false : $help->escapeEntities($title);

$useStreet = ($address->getData('country_id') == 'RU') && Mage::getStoreConfigFlag('carriers/shippingmax/search_by_street');
?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if (!empty($items)): ?>
	<input type="hidden" name="form_key" value="<?php echo $this->getFormKey() ?>" />
	<ul class="results-list">
		<?php $idx = 1; foreach ($items as $id => $item):
			$item = new Varien_Object($item); // (array) to (object)
		?>
			<li class="<?php echo ($id == $selected) ? 'item i'.$idx.' selected' : 'item i'.$idx ?>" id="pt<?php echo $id ?>" onclick="shippingmax.goToMarkerFromDetails(event, this);">
				<h2 class="name" title="<?php echo $help->escapeEntities($item->getData('name')) ?> (<?php echo $item->getId() ?>)">
					<?php if (!empty($item->getData('carrier'))): ?>
						<span class="icn ic-<?php echo str_replace(['shippingmax_', 'cash'], '', $item->getData('carrier')) ?>" title="<?php echo $help->escapeEntities(Mage::getStoreConfig('carriers/'.$item->getData('carrier').'/img_title')) ?>"></span>
					<?php elseif (!empty($title)): ?>
						<span class="icn ic-<?php echo str_replace(['shippingmax_', 'cash'], '', $code) ?>" title="<?php echo $title ?>"></span>
					<?php else: ?>
						<span class="icn ic-<?php echo str_replace(['shippingmax_', 'cash'], '', $code) ?>"></span>
					<?php endif ?>
					<span class="pname"><?php echo $item->getData('name') ?></span> <span class="pid">(<?php echo $item->getId() ?>)</span>
				</h2>
				<address class="addr">
					<?php echo preg_replace('#^\s+<br ?/?>#', '', $model->setData($item->getData())->format('html')) ?>
				</address>
				<?php if (!empty($desc = $item->getData('description'))): ?>
					<p class="desc"><?php echo $help->formatDesc($desc) ?></p>
				<?php endif ?>
				<?php if (!is_numeric($code) && (!$isShowAll || !empty($item->getData('dst')))): ?>
					<div class="action">
						<?php if (!$isShowAll): ?>
							<button type="submit" class="btn-select" onclick="this.parentNode.querySelector('input').checked = true;">
								<?php echo $this->__('Choose this location') ?>
							</button>
							<input type="radio" name="id" value="<?php echo $id ?>" <?php echo ($id == $selected) ? 'checked="checked"' : '' ?> />
						<?php endif ?>
						<?php if (!empty($item->getData('dst'))): ?>
							<div class="dist-store">
								<em><?php echo ($item->getData('dst') > 1) ? round($item->getData('dst')) : '&lt;1' ?> km</em>
							</div>
						<?php endif ?>
					</div>
				<?php endif ?>
			</li>
		<?php $idx++; endforeach ?>
	</ul>
<?php elseif (empty($address->getData('postcode')) && empty($address->getData('city'))): ?>
	<div class="box">
		<p><?php echo $useStreet ? $this->__('Please enter your street (or your postal code) and city.') : $this->__('Please enter your postal code and city.') ?></p>
	</div>
<?php elseif (empty($address->getData('postcode'))): ?>
	<div class="box">
		<p><?php echo $useStreet ? $this->__('Please enter your street (or your postal code).') : $this->__('Please enter your postal code.') ?></p>
	</div>
<?php elseif (empty($address->getData('city'))): ?>
	<div class="box">
		<p><?php echo $this->__('Please enter your city.') ?></p>
	</div>
<?php elseif (!empty($isGeoloc)): ?>
	<div class="box">
		<?php $country = $address->getData('geo_country_id'); $geoName = Mage::getModel('directory/country')->loadByCode($country)->getName(); ?>
		<?php //if ($country != $address->getData('country_id')): ?>
		<?php //else: ?>
			<p><?php echo $this->__('There are no results.') ?></p>
			<p><?php echo $this->__('Please check:') ?>
			<br />- <?php echo $this->__('your country:') ?> <strong><?php echo $geoName ?></strong>
			<br />- <?php echo ($useStreet && ($country == 'RU')) ? $this->__('your street (or postal code):') : $this->__('your postal code:') ?> <strong><?php echo $address->getData('geo_postcode') ?></strong>
			<br />- <?php echo $this->__('your city:') ?> <strong><?php echo $address->getData('geo_city') ?></strong></p>
		<?php //endif ?>
	</div>
<?php else: ?>
	<div class="box">
		<p><?php echo $this->__('There are no results.') ?></p>
		<p><?php echo $this->__('Please check:') ?>
		<br />- <?php echo $this->__('your country:') ?> <strong><?php echo $address->getCountryModel()->getName() ?></strong>
		<br />- <?php echo $useStreet ? $this->__('your street (or postal code):') : $this->__('your postal code:') ?> <strong><?php echo $address->getData('postcode') ?></strong>
		<br />- <?php echo $this->__('your city:') ?> <strong><?php echo $address->getData('city') ?></strong></p>
	</div>
<?php endif ?>